language: node_js
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
services:
  - mysql
before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart
  - npm install travis-ci
  - npm install
script:
  - echo "Login unit has been built successfully..."
notifications:
  email:
    - moro52@ess.ais.ac.nz
    - mohamed.a.rozza@gmail.com
after_success:
  - echo "Trigger login-unit build..."
  - node travis-ci-trigger.js
